// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfykdfRrWbZAMKugyveN6LtuvuFnFo9t0',
    appId: '1:384617858193:web:d731f4e15181d7f044ab30',
    messagingSenderId: '384617858193',
    projectId: 'fittrack-5c86e',
    authDomain: 'fittrack-5c86e.firebaseapp.com',
    storageBucket: 'fittrack-5c86e.appspot.com',
    measurementId: 'G-GE40QXBVYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3CNPysH9TJicGMmQYjA4AQcLzfRA8apY',
    appId: '1:384617858193:android:ab5bd867ae006cb744ab30',
    messagingSenderId: '384617858193',
    projectId: 'fittrack-5c86e',
    storageBucket: 'fittrack-5c86e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_KB8ih8y_ZrwAfxTb_T7YfNy6unAtIxw',
    appId: '1:384617858193:ios:c416169c4c2a617444ab30',
    messagingSenderId: '384617858193',
    projectId: 'fittrack-5c86e',
    storageBucket: 'fittrack-5c86e.appspot.com',
    iosClientId: '384617858193-69klvueg73jge00kfaecuhv1jcolirs8.apps.googleusercontent.com',
    iosBundleId: 'com.example.fittrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_KB8ih8y_ZrwAfxTb_T7YfNy6unAtIxw',
    appId: '1:384617858193:ios:41fab77043847dff44ab30',
    messagingSenderId: '384617858193',
    projectId: 'fittrack-5c86e',
    storageBucket: 'fittrack-5c86e.appspot.com',
    iosClientId: '384617858193-0ahup2js7av3e663rufauosn3t1rf8lo.apps.googleusercontent.com',
    iosBundleId: 'com.example.fittrack.RunnerTests',
  );
}
